name: Typescript - compile code
on:
  push:
  pull_request_target:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  ts-code-compilation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history
      - name: install meteor
        run: curl https://install.meteor.com/ | sh
      - name: run meteor npm install
        working-directory: bigbluebutton-html5
        run: meteor npm install
      - name: typescript code compilation
        working-directory: bigbluebutton-html5
        run: npx tsc